AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: hash_rockets

CyclomaticComplexity:
  Max: 11

# Configuration parameters: CountComments.
MethodLength:
  Max: 35

Metrics/PerceivedComplexity:
  Max: 15

Style/DoubleNegation:
  Enabled: false

# Configuration parameters: MaxSlashes.
Style/RegexpLiteral:
  Enabled: false
